### ISSUE TITLE
Heighten the bar on the "t" character to x-height

### ISSUE THREAD

**Issue by emilehobo** [quoteunquoteapps/CourierPrime#1]
I agree with a comment I read on this font online, stating that the horizontal bar crossing the "t" is below x-height and should be up to x-height, to make sure that the "t" is inline with the rest of the text. Other than that, love it.

**Comment by a-dg** [comment]
@emilehobo I've gone back and forth about this. I tried raising it a bit (not quite to x-height) in one version, but it wasn't right. It's not simply a matter of raising the crossbar, the rest of the character shape needs to be evaluated. Because of the weight that the crossbar carries, aligning it with the x-height makes it feel too high to me.

I admit, though, you're not alone in your thinking.

**Comment by emilehobo** [comment]
Dear Alan,

I'm sorry to some extent. You're right I'm not alone, but fonts are still to some extent expressions of a vision and subject to subjectivity. I do have my own personal opinion and can be quite strong in backing it up, but I do also respect yours and greatly appreciate the proper italics. So, keeping that in mind, thank you for the wonderful job.

Yours sincerely,


Emile M. Hobo
Diezestraat 75
7523 SL Enschede
The Netherlands

T +31(0)620126746
W http://www.linkedin.com/in/emilehobo
W http://www.facebook.com/e.m.hobo
W https://www.amazon.com/author/aemilius

- Calamo gladioque pugno. Fortuna nemini manum dat. Cursus honorum sunt. -

**Comment by emilehobo** [comment]
Just checked a number of other Courier fonts. They have the crossbar lower too. You're right. I'm wrong.
